name: test spec
on:
  push:
  pull_request:
    paths:
      - .github/workflows/test-spec.yml
      - cfn-resource-specification-json.json
      - example.yaml

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      - name: install
        run: |
          pip install cfn-lint

      - name: cfn-lint
        run: |
          cfn-lint --override-spec cfn-resource-specification-json.json example.yaml
